### ISSUE TITLE
Can you upload the other subtitles?

### ISSUE THREAD

**Issue by RecoX** [delucas/clean-coder-subtitles#1]
Hello, do you have the other subtitles for this series?? English or Spanish wherever.

I only can found this and the episode number one here   http://www.carlosble.com/2012/06/clean-coders-e1-subtitulado/

Thanks.

**Comment by delucas** [comment]
Hi @RecoX! I only transcribed and translated the 8th episode, it was done by hand... I don't have any other subtitle, I'm sorry :(
